# 1. Nginx를 기본 이미지로 사용 (경량화된 nginx:alpine 사용)
FROM nginx

# 2. 작업 디렉토리 설정
WORKDIR /app

# 2. Supervisor 설치 (필요한 프로세스 관리 도구)
RUN apt-get update && apt-get install -y \
    supervisor \
    lsof

# 3. 빌드된 실행 파일 복사
COPY canvas/dist/ /usr/share/nginx/html
COPY generator/dist/itda /app/main/generator
COPY api/dist  /app/main/api
COPY conf.d /etc/nginx/conf.d
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# 4. 실행 권한 부여
RUN chmod -R +x /app/main

ENV ITDA_CLOCK_ACG_MODE="True"
ENV ITDA_POWER_SAFETY_MODE="False"
ENV ITDA_DUT_CONN_MODE="False"
ENV ITDA_GEN_MODE="prd, doc"
ENV ITDA_HW_INTERNAL="False"
ENV ITDA_IS_PRD_MODE="True"
ENV ITDA_DOMAIN_LIST="Clock,Power,DUT,Voltage,SDC"
ENV JWT_SECRET_KEY="ITDA_SEMI"

# 5. 기본 명령어 설정
 CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]